// <auto-generated />
using System;
using LSBlueZone.API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LSBlueZone.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403183740_UpdateZonesSeed")]
    partial class UpdateZonesSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LSBlueZone.API.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Plate")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("LSBlueZone.API.Models.Parking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Parkings");
                });

            modelBuilder.Entity("LSBlueZone.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LSBlueZone.API.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerHour")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Zones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Los Santos International Airport",
                            PricePerHour = 15m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Docks",
                            PricePerHour = 8m
                        },
                        new
                        {
                            Id = 3,
                            Name = "La Puerta",
                            PricePerHour = 7m
                        },
                        new
                        {
                            Id = 4,
                            Name = "South Los Santos",
                            PricePerHour = 5m
                        },
                        new
                        {
                            Id = 5,
                            Name = "East Los Santos",
                            PricePerHour = 5m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Vespucci",
                            PricePerHour = 11m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Little Seoul",
                            PricePerHour = 9m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Downtown Los Santos",
                            PricePerHour = 10m
                        },
                        new
                        {
                            Id = 9,
                            Name = "La Mesa",
                            PricePerHour = 8m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Del Perro",
                            PricePerHour = 10m
                        },
                        new
                        {
                            Id = 11,
                            Name = "Rockford Hills",
                            PricePerHour = 12m
                        },
                        new
                        {
                            Id = 12,
                            Name = "Vinewood",
                            PricePerHour = 13m
                        });
                });

            modelBuilder.Entity("LSBlueZone.API.Models.Car", b =>
                {
                    b.HasOne("LSBlueZone.API.Models.User", "User")
                        .WithMany("Cars")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LSBlueZone.API.Models.Parking", b =>
                {
                    b.HasOne("LSBlueZone.API.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LSBlueZone.API.Models.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("LSBlueZone.API.Models.User", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
